### ISSUE TITLE
spawn autotrace ENOENT error

### ISSUE THREAD

**Issue by robert-skarzycki** [zacbarton/node-autotrace#3]
Hi,

I have simple project with index.js like this:
```
var autotrace = require('autotrace')
var input = 'test1.png'
var output = 'out.svg'

autotrace(input, {outputFile: output}, function(e, b){
    if(!err) console.log('done')
})
```

When I run ``node index.js``, I receive:
```
events.js:160
      throw er; // Unhandled 'error' event
      ^
Error: spawn autotrace ENOENT
    at exports._errnoException (util.js:1026:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:193:32)
    at onErrorNT (internal/child_process.js:359:16)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickCallback (internal/process/next_tick.js:98:9)
    at Module.runMain (module.js:606:11)
    at run (bootstrap_node.js:394:7)
    at startup (bootstrap_node.js:149:9)
    at bootstrap_node.js:509:3
```

Using Node v6.9.1, yarn 0.18.1, Windows 10 Pro x64, runnig just from cmd.
Do you have any idea how to resolve that?

**Comment by DanPuzey** [comment]
I believe you need to install the autotrace binaries found via [here](http://autotrace.sourceforge.net/) and make sure that they are available through your path. (If you can run `autotrace` from the commandline, you should be good to go.)

**Comment by ttseng** [comment]
I am also running into the same error running the demo code from the ReadMe
